"""posts table

Revision ID: 032a51d7be3f
Revises: 3cad94fe1f51
Create Date: 2023-09-07 17:29:26.608453

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "032a51d7be3f"
down_revision = "3cad94fe1f51"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("body", sa.String(length=140), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_post_timestamp"), ["timestamp"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_timestamp"))

    op.drop_table("post")
    # ### end Alembic commands ###
