"""empty message

Revision ID: 07af4cb5cfb2
Revises: 8a2b73d0ae9b
Create Date: 2023-09-13 12:57:56.169984

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "07af4cb5cfb2"
down_revision = "8a2b73d0ae9b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(sa.Column("language", sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_column("language")

    # ### end Alembic commands ###
