"""add user data

Revision ID: 83fbb00e5303
Revises: 032a51d7be3f
Create Date: 2023-09-08 17:27:00.334914

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "83fbb00e5303"
down_revision = "032a51d7be3f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("about_me", sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column("last_seen", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("last_seen")
        batch_op.drop_column("about_me")

    # ### end Alembic commands ###
